import SidebarItem from './sidebar-item.model';

export const EntitySidebarItems: SidebarItem[] = [
  {
    name: 'DashBoard',
    route: '/dashboard',
    translationKey: 'global.menu.dashboard',
    icon: 'bi bi-clipboard-data',
    submenu: [],
    authorities: ['ROLE_ADMIN'],
  },
  {
    name: 'Product',
    route: '/product',
    translationKey: 'global.menu.entities.product',
    icon: 'bi bi-bag',
    submenu: [],
    authorities: ['ROLE_ADMIN'],
  },
  {
    name: 'ProductBom',
    route: '/product-bom',
    translationKey: 'global.menu.entities.productBom',
    icon: 'bi bi-diagram-3',
    submenu: [],
    authorities: ['ROLE_ADMIN'],
  },
  {
    name: 'Inventory',
    route: '/inventory',
    translationKey: 'global.menu.entities.inventory',
    icon: 'bi bi-boxes',
    submenu: [],
    authorities: ['ROLE_ADMIN'],
  },
  {
    name: 'Customer',
    route: '/customer',
    translationKey: 'global.menu.entities.customer',
    icon: 'bi bi-person',
    submenu: [],
    authorities: ['ROLE_ADMIN'],
  },
  {
    name: 'CustomerOrder',
    route: '/customer-order',
    translationKey: 'global.menu.entities.customerOrder',
    icon: 'bi bi-cart',
    submenu: [],
    authorities: ['ROLE_ADMIN'],
  },
  {
    name: 'OrderItem',
    route: '/order-item',
    translationKey: 'global.menu.entities.orderItem',
    icon: 'bi bi-box-seam',
    submenu: [],
    authorities: ['ROLE_ADMIN'],
  },
  {
    name: 'Invoice',
    route: '/invoice',
    translationKey: 'global.menu.entities.invoice',
    icon: 'bi bi-receipt',
    submenu: [],
    authorities: ['ROLE_ADMIN'],
  },
  {
    name: 'InvoiceItem',
    route: '/invoice-item',
    translationKey: 'global.menu.entities.invoiceItem',
    icon: 'bi bi-receipt-cutoff',
    submenu: [],
    authorities: ['ROLE_ADMIN'],
  },
  {
    name: 'StockTransaction',
    route: '/stock-transaction',
    translationKey: 'global.menu.entities.stockTransaction',
    icon: 'bi bi-box',
    submenu: [],
    authorities: ['ROLE_ADMIN'],
  },
  {
    name: 'Expense',
    route: '/expense',
    translationKey: 'global.menu.entities.expense',
    icon: 'bi bi-currency-rupee',
    submenu: [],
    authorities: ['ROLE_ADMIN'],
  },
  {
    name: 'Employee',
    route: '/employee',
    translationKey: 'global.menu.entities.employee',
    icon: 'bi bi-person-vcard',
    submenu: [],
    authorities: ['ROLE_ADMIN'],
  },
];
