package com.bizflow.app.domain;

import static com.bizflow.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class InvoiceItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceItemAllPropertiesEquals(InvoiceItem expected, InvoiceItem actual) {
        assertInvoiceItemAutoGeneratedPropertiesEquals(expected, actual);
        assertInvoiceItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceItemAllUpdatablePropertiesEquals(InvoiceItem expected, InvoiceItem actual) {
        assertInvoiceItemUpdatableFieldsEquals(expected, actual);
        assertInvoiceItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceItemAutoGeneratedPropertiesEquals(InvoiceItem expected, InvoiceItem actual) {
        assertThat(actual)
            .as("Verify InvoiceItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceItemUpdatableFieldsEquals(InvoiceItem expected, InvoiceItem actual) {
        assertThat(actual)
            .as("Verify InvoiceItem relevant properties")
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()))
            .satisfies(a -> assertThat(a.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrice()))
            .satisfies(a ->
                assertThat(a.getTotalAmount())
                    .as("check totalAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalAmount())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceItemUpdatableRelationshipsEquals(InvoiceItem expected, InvoiceItem actual) {
        assertThat(actual)
            .as("Verify InvoiceItem relationships")
            .satisfies(a -> assertThat(a.getProduct()).as("check product").isEqualTo(expected.getProduct()))
            .satisfies(a -> assertThat(a.getInvoice()).as("check invoice").isEqualTo(expected.getInvoice()));
    }
}
