package com.bizflow.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StockTransactionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockTransactionAllPropertiesEquals(StockTransaction expected, StockTransaction actual) {
        assertStockTransactionAutoGeneratedPropertiesEquals(expected, actual);
        assertStockTransactionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockTransactionAllUpdatablePropertiesEquals(StockTransaction expected, StockTransaction actual) {
        assertStockTransactionUpdatableFieldsEquals(expected, actual);
        assertStockTransactionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockTransactionAutoGeneratedPropertiesEquals(StockTransaction expected, StockTransaction actual) {
        assertThat(actual)
            .as("Verify StockTransaction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockTransactionUpdatableFieldsEquals(StockTransaction expected, StockTransaction actual) {
        assertThat(actual)
            .as("Verify StockTransaction relevant properties")
            .satisfies(a -> assertThat(a.getTransactionType()).as("check transactionType").isEqualTo(expected.getTransactionType()))
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()))
            .satisfies(a -> assertThat(a.getPreviousStock()).as("check previousStock").isEqualTo(expected.getPreviousStock()))
            .satisfies(a -> assertThat(a.getNewStock()).as("check newStock").isEqualTo(expected.getNewStock()))
            .satisfies(a -> assertThat(a.getRemarks()).as("check remarks").isEqualTo(expected.getRemarks()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockTransactionUpdatableRelationshipsEquals(StockTransaction expected, StockTransaction actual) {
        assertThat(actual)
            .as("Verify StockTransaction relationships")
            .satisfies(a -> assertThat(a.getProduct()).as("check product").isEqualTo(expected.getProduct()));
    }
}
